name: Nested Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        if: ${{ github.ref_name != 'ignoreSpecConfig' }}
        with:
          # installed in previous workflow
          install: false
          working-directory: rootapp/nestedApp
          config-file: cypress.json
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run other config
        uses: cypress-io/github-action@v2
        if: ${{ github.ref_name == 'ignoreSpecConfig' }}
        with:
          install: false
          working-directory: rootapp/nestedApp
          config-file: cypress/config/ignoreNestedSpecConfig.json
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
