name: Only Run Cypress Tests not Specified in Config
# run workflow on git push and git pull
on: [push, pull_request]
jobs:
  cypress-run:
    # OS
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # split tests across three containers in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        # checks-out your repository so your workflow can access it
        uses: actions/checkout@v2
      - name: Install dependencies
        # GitHub Action for running Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run if NOT branch conditional
        uses: cypress-io/github-action@v2
        if: ${{ github.ref_name != 'conditional' }}
        with:
          # installed in previous workflow
          install: false
          record: true
          tag: ignoreSpecsFromConfigParallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}