name: Run Cypress Tests using print-env
# run workflow on git push and git pull
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Print CI env variables
        run: |
          npm i -g @bahmutov/print-env@2
          print-env GITHUB BUILD ACTIONS || true
      - name: Checkout
        # checks-out your repository so your workflow can access it
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        # GitHub Action for running Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: npx cypress info
          tag: singleMachinePrintEnv
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # running here is also fine, but you will need to look in `cypress run` instead of `Cypress tests with cypress info`
      # - name: Cypress tests with cypress info
      #   uses: cypress-io/github-action@v2
      #   with:
      #     build: npx cypress info