name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # running here is also fine, but you will need to look in `cypress run` instead of `Cypress tests with debug logs`
          # DEBUG: 'cypress:*'
      - name: Cypress tests with debug logs
        uses: cypress-io/github-action@v2
        env:
          # print all debugging
          DEBUG: 'cypress:*'